/*******************************************************************************
 * OSATE Command Line Interface
 *
 * Copyright 2026 Carnegie Mellon University.
 *
 * NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS
 * FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
 * FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
 * MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO
 * FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 *
 * Licensed under a BSD (SEI)-style license, please see LICENSE.txt
 * or contact permission@sei.cmu.edu for full terms.
 *
 * [DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited
 * distribution.  Please see Copyright notice for non-US Government use and distribution.
 *
 * This Software includes and/or makes use of Third-Party Software each subject to its own license.
 *
 * DM26-0838
 ******************************************************************************/
package org.osate.cli.server;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Path;

import org.junit.jupiter.api.Test;

/**
 * Verifies which packaged jars the embedded language server classpath accepts. The Behavior Annex
 * parser is now generated by Xtext and uses the ANTLR 3 runtime shipped as an OSGi bundle, so the
 * standalone ANTLR 4 runtime stays off the classpath and is excluded from the assembled dist.
 */
class WorkspaceServerMainTest {

	@Test
	void excludesStandaloneAntlr4Runtime() {
		assertFalse(WorkspaceServerMain.isServerRuntimeJar(Path.of("org.antlr.antlr4-runtime_4.13.2.jar")));
	}

	@Test
	void includesServerBundles() {
		assertTrue(WorkspaceServerMain.isServerRuntimeJar(Path.of("org.osate.aadl.ls_1.0.0.jar")));
		assertTrue(WorkspaceServerMain.isServerRuntimeJar(Path.of("org.antlr.runtime_3.2.0.v20230929-1400.jar")));
	}
}
