#!/usr/bin/env bash
# OSATE Command Line Interface
#
# Copyright 2026 Carnegie Mellon University.
#
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS
# FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
# MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO
# FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
#
# Licensed under a BSD (SEI)-style license, please see LICENSE.txt
# or contact permission@sei.cmu.edu for full terms.
#
# [DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited
# distribution.  Please see Copyright notice for non-US Government use and distribution.
#
# This Software includes and/or makes use of Third-Party Software each subject to its own license.
#
# DM26-0838

set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=common.sh
source "$script_dir/common.sh"

artifacts_dir="$packaging_dir/target/artifacts"
output_dir="$packaging_dir/target/recipes/homebrew"
base_url=""

usage() {
	cat <<EOF
usage: $(basename "$0") --base-url <url> [options]

Generate a Homebrew tap formula for macOS x64 and arm64 release artifacts.

Options:
  --base-url <url>       URL prefix where release artifacts are published.
                         Example: https://example.invalid/releases/v0.1
  --artifacts-dir <dir>  Directory containing artifacts and SHA256SUMS.
                         Default: $artifacts_dir
  --output-dir <dir>     Directory where Formula/osate-cli.rb is written.
                         Default: $output_dir
  --help                 Show this help.

The formula version is read from <artifacts-dir>/VERSION, written by
build-release-artifacts.sh from the built osate-cli.jar.
EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
		--base-url)
			[ $# -ge 2 ] || die "--base-url requires a value"
			base_url=$2
			shift 2
			;;
		--artifacts-dir)
			[ $# -ge 2 ] || die "--artifacts-dir requires a value"
			artifacts_dir=$2
			shift 2
			;;
		--output-dir)
			[ $# -ge 2 ] || die "--output-dir requires a value"
			output_dir=$2
			shift 2
			;;
		--help | -h)
			usage
			exit 0
			;;
		*)
			die "unknown option: $1"
			;;
	esac
done

[ -n "$base_url" ] || die "--base-url is required"

sums_file="$artifacts_dir/SHA256SUMS"
[ -f "$sums_file" ] || die "checksums file not found: $sums_file"

OSATE_CLI_VERSION=$(version_from_artifacts "$artifacts_dir")

base_url=$(strip_trailing_slash "$base_url")
mac_x64_artifact=$(artifact_filename macos-x64)
mac_arm64_artifact=$(artifact_filename macos-arm64)
mac_x64_sha=$(artifact_sha256 "$sums_file" "$mac_x64_artifact")
mac_arm64_sha=$(artifact_sha256 "$sums_file" "$mac_arm64_artifact")

[ -n "$mac_x64_sha" ] || die "checksum not found for $mac_x64_artifact"
[ -n "$mac_arm64_sha" ] || die "checksum not found for $mac_arm64_artifact"

formula_dir="$output_dir/Formula"
formula_file="$formula_dir/osate-cli.rb"
mkdir -p "$formula_dir"

{
	cat <<EOF
# Generated by osate-cli/packaging/scripts/generate-homebrew-formula.sh.
class OsateCli < Formula
  desc "$OSATE_CLI_DESCRIPTION"
EOF
	if [ -n "$OSATE_CLI_HOMEPAGE" ]; then
		printf '  homepage "%s"\n' "$OSATE_CLI_HOMEPAGE"
	fi
	cat <<EOF
  license "$OSATE_CLI_LICENSE"
  version "$OSATE_CLI_VERSION"

  on_macos do
    if Hardware::CPU.arm?
      url "$base_url/$mac_arm64_artifact"
      sha256 "$mac_arm64_sha"
    else
      url "$base_url/$mac_x64_artifact"
      sha256 "$mac_x64_sha"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"bin/osate-cli"
  end

  test do
    assert_match "usage:", shell_output("#{bin}/osate-cli --help")
  end
end
EOF
} > "$formula_file"

echo "Homebrew formula: $formula_file"
